---
# See https://github.com/jvautier/project-cli
fullname: jvautier/github-api-cli
description: github tiny api client
tags:
  - python
  - cli
  - github
  - api
github:
  has_issues: true
  has_projects: false
  has_wiki: false
